name: ytm_remote
description: A YouTube Music Remote Control.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.6
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  web:
    generate: true
    image_path: "assets/icon.jpg"
  windows:
    generate: true
    image_path: "assets/icon.jpg"
  macos:
    generate: true
    image_path: "assets/icon.jpg"
  image_path: "assets/icon.jpg"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/
